version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/your-database-name
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
